const data = [
  /*  -----------------all--------------------- */
  {
      id:1,
      categori: "All",
      nom: "tissu",
      img: "./images/tissu1.jpeg",
      prix:1000,
      quantity: 0
  },
  {
      id:2,
      categori: "All",
      nom: "sac",
      img: "./images/sac1.jpeg",
      prix:1000,
      quantity: 0
  },
  {
      id:3,
      categori: "All",
      nom: "shoes",
      img: "./images/shoes2.jpeg",
      prix:1000,
      quantity: 0
  },
  {
      id:4,
      categori: "All",
      nom: "voilée",
      img: "./images/voilée2.jpeg",
      prix:1000,
      quantity: 0
  },
  {
      id:5,
      categori: "All",
      nom: "robe",
      img: "./images/garde_robe.jpeg",
      prix:1000,
      quantity: 0
  },
  {
      id:6,
      categori: "All",
      nom: "abaya",
      img: "./images/voile2.jpeg",
      prix:1000,
      quantity: 0
  },
  {
    id: 7,
    categori: "All",
    nom: "blabla",
    img: "./images/tissu3.jpeg",
    prix: 6500,
    quantity: 0,
  },
  {
    id: 8,
    categori: "All",
    nom: "bloblo",
    img: "./images/tissu8.jpeg",
    prix: 1600,
    quantity: 0,
  },
  
  {
    id: 12,
    categori: "All",
    nom: "souuuuuuul",
    img: "./images/tissu9.jpeg",
    prix: 5000,
    quantity: 0,
  },
  {
    id: 13,
    categori: "All",
    nom: "qsdfg",
    img: "./images/robe1.jpeg",
    prix: 1000,
    quantity: 0,
  },
  {
    id: 14,
    categori: "All",
    nom: "blabla",
    img: "./images/robe2.jpeg",
    prix: 1000,
    quantity: 0,
  },
  {
    id: 15,
    categori: "All",
    nom: "robe evasée",
    img: "./images/robe3.jpeg",
    prix: 5000,
    quantity: 0,
  },
  {
    id: 16,
    categori: "All",
    nom: "Bag",
    img: "./images/sac5.jpeg",
    prix: 3000,
    quantity: 0,
  },
  {
    id: 17,
    categori: "All",
    nom: "Bag",
    img: "./images/sac6.jpeg",
    prix: 2100,
    quantity: 0,
  },
  {
    id: 18,
    categori: "All",
    nom: "Bag",
    img: "./images/sac8.jpeg",
    prix: 3000,
    quantity: 0,
  },
  
  /* ------------------fabric-------------------*/
  {
    id: 19,
    categori: "Tissu",
    nom: "blabla",
    img: "./images/tissu3.jpeg",
    prix: 6500,
    quantity: 0,
  },
  {
    id: 20,
    categori: "Tissu",
    nom: "bloblo",
    img: "./images/tissu8.jpeg",
    prix: 1600,
    quantity: 0,
  },
  {
    id: 21,
    categori: "Tissu",
    nom: "blibli",
    img: "./images/tissu10.jpeg",
    prix: 7000,
    quantity: 0,
  },
  {
    id: 22,
    categori: "Tissu",
    nom: "blanblan",
    img: "./images/tissu6.jpeg",
    prix: 2000,
    quantity: 0,
  },
  {
    id: 23,
    categori: "Tissu",
    nom: "Tissu somon",
    img: "./images/tissu4.jpeg",
    prix: 8000,
    quantity: 0,
  },
  {
    id: 24,
    categori: "Tissu",
    nom: "souuuuuuul",
    img: "./images/tissu9.jpeg",
    prix: 5000,
    quantity: 0,
  },
  {
    id: 25,
    categori: "All",
    nom: "Shoes",
    img: "./images/shoes6.jpeg",
    prix: 11000,
    quantity: 0,
  },
  {
    id: 26,
    categori: "All",
    nom: "Shoes",
    img: "./images/shoes7.jpeg",
    prix: 12000,
    quantity: 0,
  },
  {
    id: 27,
    categori: "All",
    nom: "Shoes",
    img: "./images/shoes2.jpeg",
    prix: 18000,
    quantity: 0,
  },
  /* -----------------------Dress--------------------- */
  {
    id: 28,
    categori: "Robe",
    nom: "qsdfg",
    img: "./images/robe1.jpeg",
    prix: 1000,
    quantity: 0,
  },
  {
    id: 29,
    categori: "Robe",
    nom: "blabla",
    img: "./images/robe2.jpeg",
    prix: 1000,
    quantity: 0,
  },
  {
    id: 30,
    categori: "Robe",
    nom: "robe evasée",
    img: "./images/robe3.jpeg",
    prix: 5000,
    quantity: 0,
  },
  {
    id: 31,
    categori: "Robe",
    nom: "Robe",
    img: "./images/robe4.jpeg",
    prix: 1700,
    quantity: 0,
  },
  {
    id: 32,
    categori: "Robe",
    nom: "RobeMoulente",
    img: "./images/robe5.jpeg",
    prix: 9000,
    quantity: 0,
  },
  {
    id: 33,
    categori: "Robe",
    nom: "Robe blanche forme abaya",
    img: "./images/abaya1.jpeg",
    prix: 100,
    quantity: 0,
  },
  /* -----------------------bag--------------------- */
  {
    id: 34,
    categori: "Bag",
    nom: "Bag Cure",
    img: "./images/sac2.jpeg",
    prix: 8000,
    quantity: 0,
  },
  {
    id: 35,
    categori: "Bag",
    nom: "Bag Noir",
    img: "./images/sac3.jpeg",
    prix: 1000,
    quantity: 0,
  },
  {
    id: 36,
    categori: "Bag",
    nom: "Bag Marron",
    img: "./images/sac4.jpeg",
    prix: 4000,
    quantity: 0,
  },
  {
    id: 37,
    categori: "Bag",
    nom: "Bag",
    img: "./images/sac5.jpeg",
    prix: 3000,
    quantity: 0,
  },
  {
    id: 38,
    categori: "Bag",
    nom: "Bag",
    img: "./images/sac6.jpeg",
    prix: 2100,
    quantity: 0,
  },
  {
    id: 39,
    categori: "Bag",
    nom: "Bag",
    img: "./images/sac8.jpeg",
    prix: 3000,
    quantity: 0,
  },
  /* -----------------------shoes--------------------- */
  {
    id: 40,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes1.jpeg",
    prix: 5000,
    quantity: 0,
  },
  {
    id: 41,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes4.jpeg",
    prix: 4000,
    quantity: 0,
  },
  {
    id: 42,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes5.jpeg",
    prix: 10000,
    quantity: 0,
  },
  {
    id: 43,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes6.jpeg",
    prix: 11000,
    quantity: 0,
  },
  {
    id: 44,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes7.jpeg",
    prix: 12000,
    quantity: 0,
  },
  {
    id: 45,
    categori: "Shoes",
    nom: "Shoes",
    img: "./images/shoes2.jpeg",
    prix: 18000,
    quantity: 0,
  },
];
